---
id: Compress_Fast
name: Compress_Fast
full: Fast compression library
description: >-
  A libary that provides compression suitable for packing strings on-the-fly in
  PHP code (as opposed to more resource-intensive compression algorithms such as
  DEFLATE).
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
  optional:
    ext:
      zlib: '*'
      lzf: '*'
      horde_lz4: '*'
  dev:
    composer:
      horde/test: ^3
